-- Active: 1711764182975@@127.0.0.1@1521@orcl@SYSTEM
CREATE TABLE USERS (
	id	VARCHAR(40)		NOT NULL,
	password	VARCHAR2(40)	NOT NULL,
	name	VARCHAR2(100)		NOT NULL,
	gender	VARCHAR2(100)		NULL,
	birth	VARCHAR2(100)		NOT NULL,
	mail	VARCHAR2(100)		NOT NULL,
	join_date	Date DEFAULT sysdate NOT NULL,
	reg_date	Date DEFAULT sysdate NOT NULL,
	upd_date	Date DEFAULT sysdate NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (
	id
);

